# Exercise 18

## Analyze class homeworks

In [57]:
import pandas as pd
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt

data = pd.read_excel('E18.xlsx')
data.head()

,Sexo,T1,T2,T3,T4,T5,T6
0,H,Un científico de datos y un ingeniero de datos...,NaN,Los árboles de decisión es uno de los algoritm...,NaN,"En el documento ""Do We Need Hundreds of Classi...",Boosting builds models from individual so call...
1,H,Aunque los dos perfiles cuentan con habilidade...,Aunque el conceso no es total en el tema de ma...,NaN,En Machine Learing el propósito de los métodos...,El paper publicado en 2014 hace una evaluación...,Gradient Boosting ClassifierGradient Boosting ...
2,H,Python vs Stata. Analizar información es un pr...,En el marco del Machine Learning encontramos c...,Árbol de clasificación Como su nombre lo indic...,Este es un mecanismo que utiliza varios algori...,El paper analiza 179 clasificadores de 17 dife...,Gradient Boosting Classifier busca aprender de...
3,M,Los algoritmos de machine learning buscan pred...,Los algoritmos de machine learning buscan pred...,Los arboles de decisión pertenecen a los algor...,Consideremos el siguiente ejemplo: Una persona...,¿Se necesitan cientos de modelos para resolver...,NaN
4,H,Python vs R para análisis de datos. A pesar de...,Tipos de aprendizaje en Machine Learning. El M...,Tipos de árboles de decisión y aplicaciones. U...,La combinación de modelos o ensemble es un mod...,En el articulo se analizan cerca de 180 clasif...,XGBoosting vs GBoosting. A pesar de que el alg...

# Exercise 18.1

Analyze the writing patterns of each student

In [98]:
from collections import Counter
import warnings
warnings.filterwarnings('ignore')

In [83]:
def word_stats(word_counts):     # word_counts = count_words_fast(text)    
    num_unique = len(word_counts) 
    counts = word_counts.values() 
    return (num_unique, counts)

In [118]:
#data_h=data[data['Sexo']=='H']
data['Texto'] = data.iloc[:,1].str.cat(data.iloc[:,2],sep=" ", na_rep=' ').\
                str.cat(data.iloc[:,3],sep=" ", na_rep='').str.cat(data.iloc[:,4],sep=" ", na_rep=' ').\
                str.cat(data.iloc[:,5],sep=" ", na_rep='').str.cat(data.iloc[:,6],sep=" ", na_rep=' ')
data_g=data[['Sexo','Texto']]

In [126]:
data_g['Palabras']=''
data_g['Palabras_unicas']=''
data_g['comas']=''
data_g['puntos']=''
data_g['tildes']=''

for i in range(0,len(data_g)):
    word_counts = count_words_fast(data_g['Texto'][i])
    (num_unique, counts) = word_stats(word_counts)
    data_g['Palabras'][i]=sum(counts)
    data_g['Palabras_unicas'][i]=num_unique
    data_g['comas'][i]=data_g['Texto'][i].count(",")
    data_g['puntos'][i]=data_g['Texto'][i].count(".")
    data_g['tildes'][i]=data_g['Texto'][i].count("á")+data_g['Texto'][i].count("é")+\
    data_g['Texto'][i].count("í")+data_g['Texto'][i].count("ó")+data_g['Texto'][i].count("ú")

data_g['Palabras']=pd.to_numeric(data_g['Palabras'])
data_g['Palabras_unicas']=pd.to_numeric(data_g['Palabras_unicas'])

In [145]:
data_g

,Sexo,Texto,Palabras,Palabras_unicas,comas,puntos,tildes
0,H,Un científico de datos y un ingeniero de datos...,1851,805,131,92,165
1,H,Aunque los dos perfiles cuentan con habilidade...,1325,574,24,55,137
2,H,Python vs Stata. Analizar información es un pr...,1772,652,75,58,147
3,M,Los algoritmos de machine learning buscan pred...,1471,629,68,56,144
4,H,Python vs R para análisis de datos. A pesar de...,1671,610,68,46,141
5,H,Siendo dos grandes software's de analítica los...,1237,537,61,65,162
6,H,Data Scientist y Data Engineer son dos profesi...,1266,604,69,71,22
7,M,Las diferencias de un científico de datos y un...,2001,759,110,67,197
8,H,Uno de los criterios más importantes en la sel...,1345,541,74,40,102
9,H,Diferencia entre un científico de datos y un i...,1869,691,85,34,169
10,H,Existen diferencias significativas en el perfi...,1548,532,49,32,132
11,H,Por un lado los ingenieros de datos se centra...,2163,860,79,89,173
12,H,Diferencias entre los científicos de datos y l...,1707,660,93,68,138
13,H,La diferencia entre un data scientist y un dat...,1568,632,39,31,133
14,H,Los algoritmos de Machine Learning tienen como...,536,259,46,16,49
15,M,Machine Learning es un método de análisis de i...,1402,630,56,60,19
16,M,Analytics ha tenido una tendencia exponencial ...,1461,608,76,54,164
17,H,El duelo entre Data Engineer vs Data Scientist...,2495,870,129,92,229
18,H,Los ingenieros de datos tienen como responsabi...,1216,510,55,35,123
19,H,Los data scientist y data engineers están embe...,1086,487,67,51,107
20,H,La ciencia de datos ha evolucionado mucho a tr...,1135,441,15,29,95
21,H,La creación eficiente de modelos no garantiza ...,3512,1167,175,133,258
22,H,Un ingeniero de datos es la persona que se enc...,657,332,51,22,69
23,H,Para la mayoría de las personas son roles que ...,1264,558,54,57,116
24,H,En la actualidad se cuentan con grandes cantid...,1485,619,105,52,132
25,H,Python vs R vs SAS for Data Science. Cuando se...,1861,610,57,23,160
26,H,"Hoy en día, es común en las empresas y grandes...",2105,847,140,69,189
27,H,Los arboles de decisión constituyen una he...,880,426,46,56,75
28,M,Pese a que la ciencia de datos y la ingeniería...,1060,463,84,34,31
29,H,"En términos de costo, SAS es un software comer...",1864,752,134,68,160
30,H,Las diferencias entre un científico de datos y...,1384,526,73,52,124
31,H,Dos de las principales razones por las que a p...,1424,609,108,30,115
32,H,Entre los programas más populares para realiza...,1146,499,70,34,92
33,M,"Actualmente para las empresas, los científicos...",1820,726,96,87,227
34,H,Un ingeniero de datos es quien se encarga de l...,1802,692,66,101,160
35,H,Un ingeniero de datos está encargado de la inf...,1360,596,94,58,125
36,H,Diferencia entre un Científico de Datos y un I...,2004,851,86,38,166
37,H,El ingeniero de datos se encarga de la arquite...,2234,892,119,82,246
38,H,A data Engineer is a support role in the Analy...,221,114,7,13,0
39,M,El ingeniero de datos y el científicos de da...,2111,831,81,47,228
40,M,"Cuando se habla de un Data Engineer, se consid...",1486,568,66,49,150
41,H,Aunque un científico de datos y un ingeniero d...,1325,520,70,55,142

In [143]:
#Descriptivos Hombres
data_g[data_g['Sexo']=='H'].describe()

          Palabras  Palabras_unicas       comas      puntos      tildes
count    34.000000        34.000000   34.000000   34.000000   34.000000
mean   1538.764706       613.970588   76.882353   54.323529  133.911765
std     598.648987       197.853709   37.003493   26.648919   54.850965
min     221.000000       114.000000    7.000000   13.000000    0.000000
25%    1243.750000       521.500000   54.250000   34.000000  109.000000
50%    1454.500000       606.500000   70.000000   53.500000  135.000000
75%    1858.500000       691.750000   93.750000   68.000000  161.500000
max    3512.000000      1167.000000  175.000000  133.000000  258.000000

In [144]:
#Descriptivos Mujeres
data_g[data_g['Sexo']=='M'].describe()

          Palabras  Palabras_unicas       comas     puntos      tildes
count     8.000000         8.000000    8.000000   8.000000    8.000000
mean   1601.500000       651.750000   79.625000  56.750000  145.000000
std     348.479555       116.307167   17.336481  15.636496   80.689883
min    1060.000000       463.000000   56.000000  34.000000   19.000000
25%    1446.250000       598.000000   67.500000  48.500000  115.750000
50%    1478.500000       629.500000   78.500000  55.000000  157.000000
75%    1865.250000       734.250000   87.000000  61.750000  204.500000
max    2111.000000       831.000000  110.000000  87.000000  228.000000

# Exercise 18.2

Evaluate the similarities of the homeworks of the students

tip: https://github.com/orsinium/textdistance

In [250]:
import textdistance

In [252]:
df=pd.DataFrame()
simil={}
for i in range(0,len(data_g)):
    lista=[]
    for j in range(0,len(data_g)):
        lista.append(textdistance.hamming.normalized_similarity(data_g['Texto'][i],data_g['Texto'][j]))
    df[i]=lista

In [259]:
df

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,1.000000,0.049650,0.070201,0.055349,0.061825,0.049909,0.051377,0.062216,0.053881,0.065556,...,0.040756,0.067880,0.067870,0.056731,0.065162,0.058612,0.008376,0.061116,0.057163,0.052241
1,0.049650,1.000000,0.055731,0.061405,0.060511,0.067387,0.064100,0.049600,0.067269,0.055097,...,0.064334,0.056822,0.051957,0.063299,0.046301,0.039651,0.013736,0.048953,0.070819,0.076896
2,0.070201,0.055731,1.000000,0.064374,0.071126,0.045287,0.045827,0.066134,0.052489,0.064875,...,0.049698,0.069326,0.064773,0.054650,0.062998,0.054875,0.008373,0.062167,0.059512,0.055821
3,0.055349,0.061405,0.064374,1.000000,0.068319,0.055984,0.059946,0.054615,0.065784,0.057308,...,0.048582,0.055121,0.058452,0.066827,0.054418,0.047125,0.011259,0.056010,0.068182,0.062344
4,0.061825,0.060511,0.071126,0.068319,1.000000,0.053972,0.057876,0.063470,0.056510,0.060964,...,0.053191,0.063627,0.061915,0.062854,0.058051,0.050723,0.011126,0.054734,0.071638,0.059731
5,0.049909,0.067387,0.045287,0.055984,0.053972,1.000000,0.064014,0.040197,0.064973,0.047615,...,0.063165,0.049166,0.051957,0.056471,0.045606,0.037506,0.012025,0.039342,0.056741,0.067226
6,0.051377,0.064100,0.045827,0.059946,0.057876,0.064014,1.000000,0.044507,0.067454,0.047530,...,0.057588,0.049507,0.048060,0.061132,0.041432,0.039236,0.010010,0.041294,0.058980,0.063731
7,0.062216,0.049600,0.066134,0.054615,0.063470,0.040197,0.044507,1.000000,0.046623,0.062764,...,0.040903,0.069111,0.065429,0.053518,0.068177,0.064701,0.007679,0.070351,0.052186,0.044899
8,0.053881,0.067269,0.052489,0.065784,0.056510,0.064973,0.067454,0.046623,1.000000,0.049741,...,0.064146,0.054695,0.054209,0.059614,0.048543,0.042488,0.012286,0.041670,0.062820,0.072119
9,0.065556,0.055097,0.064875,0.057308,0.060964,0.047615,0.047530,0.062764,0.049741,1.000000,...,0.039708,0.068787,0.070062,0.059434,0.069954,0.063871,0.007397,0.066522,0.060199,0.056798
10,0.058631,0.064832,0.063473,0.069001,0.074663,0.060454,0.059725,0.056417,0.064728,0.062410,...,0.058891,0.058268,0.061223,0.072754,0.054263,0.052730,0.010423,0.053683,0.071607,0.065458
11,0.052500,0.043655,0.060418,0.051858,0.053713,0.038519,0.044939,0.065554,0.043512,0.059205,...,0.037877,0.059491,0.055781,0.047721,0.069548,0.064079,0.006420,0.063271,0.050075,0.047792
12,0.064589,0.054645,0.071486,0.064857,0.067276,0.050166,0.051599,0.060884,0.052316,0.073123,...,0.048464,0.067625,0.068583,0.056168,0.062379,0.054045,0.009764,0.062017,0.063424,0.059124
13,0.063898,0.058384,0.061043,0.066446,0.072372,0.052555,0.055372,0.062529,0.064018,0.065386,...,0.051875,0.066689,0.058538,0.061201,0.063616,0.050862,0.010492,0.056386,0.063532,0.063144
14,0.022278,0.030641,0.023949,0.028878,0.025376,0.032658,0.031018,0.020686,0.029179,0.020491,...,0.034805,0.021436,0.023640,0.027206,0.019943,0.018407,0.026773,0.018770,0.027730,0.028894
15,0.053795,0.066357,0.053660,0.064324,0.060609,0.061941,0.061148,0.047015,0.070207,0.056118,...,0.056505,0.053675,0.053169,0.061023,0.048079,0.040274,0.012230,0.047451,0.067726,0.069641
16,0.055004,0.067233,0.055461,0.065992,0.062268,0.063435,0.059750,0.050776,0.065557,0.053907,...,0.055059,0.053760,0.054988,0.066117,0.050475,0.043180,0.012397,0.045649,0.066233,0.066227
17,0.048175,0.039319,0.052823,0.044093,0.051127,0.036932,0.038440,0.053703,0.037749,0.057346,...,0.033980,0.053075,0.051693,0.042083,0.053703,0.065134,0.007349,0.062559,0.046165,0.038628
18,0.044210,0.067269,0.051769,0.063386,0.051337,0.067975,0.066485,0.043097,0.065210,0.048635,...,0.064363,0.047125,0.046069,0.058639,0.041586,0.041174,0.012156,0.045649,0.060154,0.067109
19,0.040670,0.056821,0.041775,0.052648,0.046262,0.060886,0.056105,0.037612,0.057531,0.039622,...,0.076118,0.039469,0.045203,0.052894,0.036948,0.034807,0.016839,0.036790,0.056421,0.054643
20,0.047664,0.059169,0.047988,0.054003,0.053191,0.061139,0.059441,0.040668,0.058476,0.045064,...,0.067689,0.048231,0.046155,0.055712,0.041818,0.033700,0.013188,0.039342,0.053434,0.061051
21,0.035910,0.026083,0.038763,0.033193,0.033736,0.027306,0.025766,0.041163,0.027351,0.039895,...,0.021917,0.038718,0.036453,0.028665,0.042703,0.049586,0.004664,0.043427,0.030159,0.027487
22,0.025214,0.034867,0.027370,0.027836,0.031134,0.038228,0.032130,0.023977,0.038512,0.024488,...,0.041737,0.027390,0.026065,0.034034,0.020329,0.022075,0.026460,0.021098,0.033703,0.035768
23,0.050859,0.063982,0.051499,0.059112,0.058462,0.064956,0.066415,0.047641,0.065918,0.046340,...,0.064591,0.047805,0.056027,0.061782,0.046765,0.038959,0.012651,0.043772,0.064420,0.065478
24,0.058544,0.069676,0.063113,0.070475,0.066465,0.054956,0.066514,0.053126,0.062916,0.056373,...,0.055719,0.052484,0.056547,0.074138,0.054881,0.047125,0.011449,0.050980,0.074872,0.072075
25,0.071669,0.059623,0.068515,0.059711,0.065028,0.050732,0.049338,0.067231,0.055091,0.073378,...,0.041841,0.069411,0.073606,0.057880,0.063461,0.057643,0.007932,0.065921,0.066074,0.056573
26,0.060667,0.042519,0.056370,0.054074,0.052519,0.040444,0.039037,0.064000,0.044667,0.060667,...,0.038148,0.062741,0.059333,0.047630,0.067630,0.066155,0.007556,0.075852,0.047704,0.048370
27,0.033417,0.049425,0.038084,0.042640,0.037380,0.048481,0.047701,0.033537,0.050089,0.032055,...,0.053763,0.035726,0.034811,0.046933,0.032388,0.027195,0.014953,0.032735,0.044902,0.047303
28,0.040238,0.055764,0.049068,0.049208,0.046164,0.055823,0.049926,0.038003,0.056113,0.038942,...,0.068053,0.040235,0.040700,0.051377,0.037412,0.034600,0.016403,0.035513,0.051408,0.052662
29,0.070844,0.052098,0.065862,0.060711,0.062991,0.042388,0.046525,0.067544,0.051169,0.071097,...,0.040446,0.072363,0.071688,0.056742,0.065239,0.056813,0.007599,0.065245,0.059107,0.053956
30,0.052932,0.075834,0.054650,0.068286,0.060511,0.067993,0.067408,0.048503,0.070685,0.052376,...,0.057812,0.054440,0.052390,0.067743,0.048620,0.043180,0.009713,0.048352,0.068046,0.072818
31,0.053709,0.073168,0.059152,0.064846,0.064415,0.063180,0.064976,0.054223,0.067669,0.054162,...,0.059253,0.056312,0.056547,0.072187,0.046920,0.044149,0.013579,0.047301,0.067513,0.064751
32,0.040756,0.064334,0.049698,0.048582,0.053191,0.063165,0.057588,0.040903,0.064146,0.039708,...,1.000000,0.040320,0.047368,0.055821,0.040736,0.036952,0.012592,0.041895,0.059727,0.059536
33,0.067880,0.056822,0.069326,0.055121,0.063627,0.049166,0.049507,0.069111,0.054695,0.068787,...,0.040320,1.000000,0.069581,0.055461,0.062766,0.058197,0.010122,0.065470,0.053760,0.053079
34,0.067870,0.051957,0.064773,0.058452,0.061915,0.051957,0.048060,0.065429,0.054209,0.070062,...,0.047368,0.069581,1.000000,0.058105,0.064853,0.061380,0.009699,0.053983,0.059404,0.057846
35,0.056731,0.063299,0.054650,0.066827,0.062854,0.056471,0.061132,0.053518,0.059614,0.059434,...,0.055821,0.055461,0.058105,1.000000,0.044292,0.046433,0.010839,0.048953,0.071246,0.064492
36,0.065162,0.046301,0.062998,0.054418,0.058051,0.045606,0.041432,0.068177,0.048543,0.069954,...,0.040736,0.062766,0.064853,0.044292,1.000000,0.061172,0.008116,0.069224,0.052717,0.050475
37,0.058612,0.039651,0.054875,0.047125,0.050723,0.037506,0.039236,0.064701,0.042488,0.063871,...,0.036952,0.058197,0.061380,0.046433,0.061172,1.000000,0.005744,0.061103,0.047263,0.045810
38,0.008376,0.013736,0.008373,0.011259,0.011126,0.012025,0.010010,0.007679,0.012286,0.007397,...,0.012592,0.010122,0.009699,0.010839,0.008116,0.005744,1.000000,0.007058,0.011625,0.012117
39,0.061116,0.048953,0.062167,0.056010,0.054734,0.039342,0.041294,0.070351,0.041670,0.066522,...,0.041895,0.065470,0.053983,0.048953,0.069224,0.061103,0.007058,1.000000,0.053157,0.044072
40,0.057163,0.070819,0.059512,0.068182,0.071638,0.056741,0.058980,0.052186,0.062820,0.060199,...,0.059727,0.053760,0.059404,0.071246,0.052717,0.047263,0.011625,0.053157,1.000000,0.066233
41,0.052241,0.076896,0.055821,0.062344,0.059731,0.067226,0.063731,0.044899,0.072119,0.056798,...,0.059536,0.053079,0.057846,0.064492,0.050475,0.045810,0.012117,0.044072,0.066233,1.000000

# Exercise 18.3

Create a classifier to predict the sex of each student

In [302]:
from sklearn.feature_extraction.text import TfidfVectorizer

X=data_g.Texto
y=data_g.Sexo

vect = TfidfVectorizer()
X_dtm = vect.fit_transform(X)

In [303]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X_dtm, y, test_size=0.33, random_state=1)

clf=RandomForestClassifier(n_jobs=-1, n_estimators=100, max_depth=10, random_state=42).fit(X_train,y_train)
y_pred=clf.predict(X_test)

accuracy_score(y_test,y_pred)

0.7857142857142857